library-updater:
  image: node:6.6.0
  working_dir: /
  #volumes:
  #  - ./:/
  #  - ./data/music:./music/ #TODO FORMAT THIS BETTER
  links:
    - database

database:
  image: mongo:3.2
  command: mongod --smallfiles --quiet --logpath=/dev/null
  volumes:
    - ./data/db:/data/db
  ports:
    - "27017:27017"